name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
        # For future flexibility, you can add more node versions like '18.x', '16.x', etc.
        # Example: node-version: ['16.x', '18.x', '20.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # This will cache npm dependencies

    - name: Install dependencies
      run: npm ci  # Clean install from package-lock.json

    - name: Build the project
      run: npm run build --if-present  # Build only if a build script is defined

    - name: Run tests
      run: npm test  # Run tests
